### PR TITLE
ZF3 compatibility 

### PR DESCRIPTION
**Pull request by kokspflanze**
hi,

added full ZF3 support, dropped ZF2-eventmanager and set min PHP5.6

changed autoloader to PSR-4
added php-nightly in travis

i stuck atm @ hhvm UnitTests, mabye someone can help.

for testing you can add following in your composer.json `"kokspflanze/bjy-authorize": "~1.6"`

### CODE REVIEW

**Comment by jarrettj** [comment]
Hi guys, just wanted to know when this PR will be merged in? Thanks.

**Comment by kokspflanze** [comment]
@jarrettj you can use `"kokspflanze/bjy-authorize": "~1.6"` while zf3 is not supported.

**Comment by jarrettj** [comment]
Thanks.

**Comment by aight8** [comment]
Any news?

**Comment by jarrettj** [comment]
@aight8 "kokspflanze/bjy-authorize": "~1.6" works for me :)

**Comment by robob4him** [comment]
@kokspflanze, you'll also want to update Guard/Route:138 and Guard/Controller:173. In ZF2 the EventManager::trigger call would determine whether you had passed an event instance and trigger using that event. In ZF3 the EventManager::trigger method is only if you want EventManager to create an event for you. In both of these cases I think your intent is to trigger the MvcEvent with a different name. If so, you should instead set the name on the event and call EventManager::triggerEvent and the EventManager will pass the event as-is.

The only reason I say this is because we have handlers for the MvcEvent and BjyAuthorize event names and the handler failed because EventManager had wrapped the original MvcEvent in a normal Event and passed it along.

**Comment by kokspflanze** [comment]
@robob4him i will fix this, next week i have a bit time, maybe you can later test ist too =]

**Comment by robob4him** [comment]
Gladly!

-----Original Message-----

**Comment by aight8** [comment]
Any news?

**Comment by kokspflanze** [comment]
@aight8 you can use my fork for ypur project.

**Comment by jarrettj** [comment]
+1 @aight8

**Comment by j-schumann** [comment]
+1 for merge

**Comment by kokspflanze** [comment]
@j-schumann if you want you can make a PR to my repository to fix this problem

**Comment by j-schumann** [comment]
PR sent, contains no testing for the added functionality.
Also does not fix the the included default UnauthorizedStrategy / RedirectionStrategy, those should probably add ``return $response; `` as last line in ``onDispatchError()``

**Comment by ivok** [comment]
@kokspflanze I used this module in zf2. Now I use yout fork in ZF3 project but encountered some problems. Basically I used old configuration of controllers, roles, resurces and etc... In the DB I defined 3 roles. Guest, User and Admin, as Admin role is children of User. But when try to guard admin controller only for 'admin' role, it says allwas forbiden. I am sure that user has role 'admin'. What I sow, is that no other roles except guest and user are working. Neither rule and resource providers. I cant figure it out whats going on.

**Comment by kokspflanze** [comment]
@ivok can you maybe post your config?

**Comment by ivok** [comment]
```php
'bjyauthorize' => [
        'default_role' => 'guest',
        'identity_provider' => 'BjyAuthorize\Provider\Identity\AuthenticationIdentityProvider',
        'role_providers' => [
            'BjyAuthorize\Provider\Role\ObjectRepositoryProvider' => [
                'object_manager' => 'Doctrine\ORM\EntityManager',
                'role_entity_class' => 'Application\Entity\Role',
            ],
        ],
        'guards' => [
            'BjyAuthorize\Guard\Controller' => [
                ...
                [
                    'controller' => \Application\Controller\IndexController::class,
                    'roles' => ['user'],
                ],
                [
                    'controller' => \Admin\Controller\IndexController::class,
                    'roles' => ['admin'],
                ],
                //Zfcuser Controller
                [
                    'controller' => 'zfcuser',
                    'roles' => []
                ],
            ],
        ],
        'resource_providers' => [
           ...
           'admin-menu' => [],
        ],
        'rule_providers' => [
            ...
            [['admin'], 'admin-menu'],
        ],
    ],
```
id | parent_id | roleid
------------ | ------------- | -------------
1             |                  | guest
2             |                  | user
3             | 2 | admin

```php
'controllers' => [
        'factories' => [
           //This is Admin\Controller\IndexController
            Controller\IndexController::class => ControllerFactory::class,
        ],
    ],
```

**Comment by kokspflanze** [comment]
@ivok i tested it with https://github.com/kokspflanze/pserverCMSFull/blob/develop/config/autoload/bjyauthorize.global.php with same table like in your example, but all works fine for me.

did you use for testing the zf-toolbar? you can also add pm me in gitter to search the problem.

**Comment by ivok** [comment]
@kokspflanze I found my mistake. Before using you module, I was created a simpler listener to detect where user has rights for some controller or not. I stored the roles of the users as serialized array instead of object relations and forgot tho change the implementation of method getRoles() to return ArrayCollection of Role object. It was returning array! Sorry for bothering you and thank you for your help.

**Comment by MethorZ** [comment]
Are there any plans on merging this or is there still stuff to do? (:

**Comment by kokspflanze** [comment]
@MethorZ from my site is everything done, expected the shitty hhvm-test

like i wrote you can also use my fork until we wait for feedback.

**Comment by thomasvargiu** [comment]
I'm using this branch in my big project and everything is ok.

Would be awesome if this will be merged and tagged.

Ping @bjyoungblood @Ocramius

**Comment by stijnhau** [comment]
What is the status for this merge?

**Comment by stijnhau** [comment]
Can this be merged cause no zf3 support is strange now.

**Comment by kokspflanze** [comment]
@stijnhau you can use my fork just add `"kokspflanze/bjy-authorize": "^1.6.3"` in your composer json, you can use it with zf2 and zf3

**Comment by stijnhau** [comment]
@kokspflanze thats what i doi but this hould be officialy supported in the base module

**Comment by robob4him** [comment]
Due to the passive attitude toward forward progress by the author I think it's fair to assume this module has been deprecated for all uses except ZF2 projects.

-----Original Message-----

**Pull request closed without merging**
