### PR TITLE
Fix issue #300 - Unauthorized is a word and should not be CamelCased as if it were two words

### PR DESCRIPTION
**Pull request by kler**
Fix issue #300 - Unauthorized is a word and should not be CamelCased as if it were two words

### CODE REVIEW

**Comment by kler** [comment]
php 5.3.3 fails because of nonexistent openssl extension :/
All other php versions succeeds.

**Comment by Ocramius** [comment]
While this may well be a bug, this is a BC break, as it is modifying a symbol that may be referenced by external consumers of the lib. I have to reject the PR and the issue, sorry.

**Comment by kler** [comment]
Thing is we're dealing with php here, someone took the random design decision to make classes case insensitive :) so I'm pretty sure the case of the exception could be changed without affecting any running code. php won't even let you declare same class with different case. See https://3v4l.org/OGXb1

**Comment by Ocramius** [comment]
>  to make classes case insensitive

That doesn't work with the autoloader, sadly. Case-sensitive filesystems would have a hard failure when trying to instantiate `UnAuthorizedException`, while `UnauthorizedException.php` is the file on the fs.

**Comment by kler** [comment]
Ok, I see. Thx for your time and comments!

**Comment by Ocramius** [comment]
@kler #phpsadness, heh...

**Pull request closed without merging**
